spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password:

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}